import fs from "node:fs";
import assert from "node:assert/strict";
import path from "node:path";
import crypto from "node:crypto";

const source = fs.readFileSync("native/knmon-agent64/src/AgentMain.cpp", "utf8");
const pattern = /HookDefinition\s*\{\s*"([^"]+)",\s*"([^"]+)",\s*reinterpret_cast<void\*>\(([^)]+)\),\s*reinterpret_cast<void\*\*>\(&([^)]+)\)/gu;
const bindings = Array.from(source.matchAll(pattern), ([, module, name, wrapper, original]) => ({ module, name, wrapper, original }));
assert.equal(bindings.length, Array.from(source.matchAll(/HookDefinition\s*\{\s*"/gu)).length);
assert.ok(bindings.length > 300);
const lines = ["// Generated by tools/def-validator/generate-sdk-abi.mjs."];
const sdkAliases = { EnumProcessModules: "K32EnumProcessModules", GetModuleBaseNameW: "K32GetModuleBaseNameW",
  GetModuleFileNameExW: "K32GetModuleFileNameExW", GetModuleInformation: "K32GetModuleInformation",
  GdipCreateHalftonePalette: "Gdiplus::DllExports::GdipCreateHalftonePalette" };
for (const { module, name, wrapper, original } of bindings)
{
  lines.push(`static_assert(std::is_same_v<decltype(&${wrapper}), decltype(${original})>, "Wrapper/original ABI: ${module}!${name}");`);
  if (["LdrLoadDll", "LdrGetProcedureAddress"].includes(name))
  {
    lines.push(`static_assert(std::is_same_v<decltype(&${wrapper}), knmon::native_abi::${name}>, "Pinned native ABI: ${module}!${name}");`);
  }
  else
  {
    lines.push(`static_assert(std::is_same_v<decltype(&${wrapper}), decltype(&::${sdkAliases[name] ?? name})>, "Windows SDK ABI: ${module}!${name}");`);
  }
}
function output(file, value)
{
  if (process.argv.includes("--check"))
  {
    assert.equal(fs.readFileSync(file, "utf8").replaceAll("\r\n", "\n"), value, `${file} is stale.`);
  }
  else
  {
    fs.writeFileSync(file, value);
  }
}
output("native/knmon-agent64/src/GeneratedSdkAbiChecks.inc", `${lines.join("\n")}\n`);
const native = JSON.parse(fs.readFileSync("generated/phnt-ntdll-prototype-index.json"));
const nativeNames = ["LdrLoadDll", "LdrGetProcedureAddress"];
const prototypes = nativeNames.map((name) => native.prototypes.find((entry) => entry.name === name));
assert.equal(native.source.commit, "53fbbdc5b5d2b08761db1c7b26bfa8c820924356", "Review changed native ABI provenance.");
assert.ok(prototypes.every((entry) => entry?.callingConvention === "ntapi" && entry.parameters.length === 4));
const nativeTypes = { PCUNICODE_STRING: "const UNICODE_STRING*", PCANSI_STRING: "const ANSI_STRING*" };
output("native/knmon-common/include/knmon/common/NativeApiAbi.h", [
  "// Generated from pinned PHNT prototypes by tools/def-validator/generate-sdk-abi.mjs.",
  "#pragma once", "#include <Windows.h>", "#include <winternl.h>", "", "namespace knmon::native_abi", "{",
  ...prototypes.map((entry) => `using ${entry.name} = ${entry.returnType}(NTAPI*)(${entry.parameters.map((parameter) =>
    nativeTypes[parameter.type] ?? parameter.type).join(", ")});`), "}", ""
].join("\n"));
const toolchain = JSON.parse(fs.readFileSync("toolchain.json"));
const ir = { schemaVersion: 1, sdk: toolchain.windowsSdk, compilerToolset: toolchain.toolset,
  architectures: ["x86", "x64"], nativeSource: native.source, nativePrototypes: prototypes,
  requiredChecks: ["compiler_type_equality", "differential_corpus", "negative_controls"],
  bindings: bindings.map((binding) => ({ ...binding,
    authority: nativeNames.includes(binding.name) ? "pinned_phnt" : "windows_sdk",
    sdkSymbol: nativeNames.includes(binding.name) ? null : sdkAliases[binding.name] ?? binding.name,
    runtimeVerification: "not_implied_by_compiler_check" })) };
output("generated/sdk-abi-ir.json", `${JSON.stringify(ir, null, 2)}\n`);
if (process.argv.includes("--pin-sdk") || process.argv.includes("--verify-sdk"))
{
  const sdkRoot = process.env.KNMON_SDK_INCLUDE ?? `C:/Program Files (x86)/Windows Kits/10/Include/${toolchain.windowsSdk}`;
  const pending = [source, fs.readFileSync("native/knmon-common/include/knmon/common/NativeApiAbi.h", "utf8")];
  const files = new Map();
  while (pending.length !== 0)
  {
    for (const [, name] of pending.pop().matchAll(/^\s*#\s*include\s*[<"]([^>"]+)[>"]/gmu))
    {
      const file = ["um", "shared", "ucrt", "winrt"].map((part) => `${part}/${name.replaceAll("\\", "/")}`)
        .find((relative) => fs.existsSync(path.join(sdkRoot, relative)));
      if (file !== undefined && !files.has(file.toLowerCase()))
      {
        const bytes = fs.readFileSync(path.join(sdkRoot, file));
        files.set(file.toLowerCase(), { file, sha256: crypto.createHash("sha256").update(bytes).digest("hex") });
        pending.push(bytes.toString("utf8"));
      }
    }
  }
  const hashes = Array.from(files.values()).sort((a, b) => a.file.localeCompare(b.file, "en"));
  const file = "generated/sdk-abi-sources.json";
  const text = `${JSON.stringify({ sdk: toolchain.windowsSdk, nativeSource: native.source,
    nativePrototypeSha256: crypto.createHash("sha256").update(JSON.stringify(prototypes)).digest("hex"), sdkHeaders: hashes }, null, 2)}\n`;
  if (process.argv.includes("--pin-sdk"))
  {
    fs.writeFileSync(file, text);
  }
  else
  {
    assert.equal(fs.readFileSync(file, "utf8").replaceAll("\r\n", "\n"), text, "SDK header provenance changed.");
  }
  console.log(`SDK provenance: ${hashes.length} headers`);
}
console.log(`SDK ABI bindings: ${bindings.length}`);
