// Generated by tools/def-validator/generate-typed-abi.mjs.
#pragma once
#include <cstdint>

namespace knmon
{
enum class TypedValueKind : std::uint32_t
{
    Void, Unsigned32, Signed32, SignedPointer, Pointer, Float32, Float64, Point2F, Color4F
};
struct TypedAbiMetadata
{
    std::uint16_t Id;
    const char* Module;
    const char* Name;
    TypedValueKind ReturnKind;
    std::uint32_t ArgumentCount;
    TypedValueKind Arguments[3];
};
inline constexpr TypedAbiMetadata TypedAbiContracts[] =
{
    { 26649, "oleaut32.dll", "VarR8FromR4", TypedValueKind::Signed32, 2, { TypedValueKind::Float32, TypedValueKind::Pointer } },
    { 26647, "oleaut32.dll", "VarR4FromR8", TypedValueKind::Signed32, 2, { TypedValueKind::Float64, TypedValueKind::Pointer } },
    { 10404, "d2d1.dll", "D2D1ConvertColorSpace", TypedValueKind::Color4F, 3, { TypedValueKind::Unsigned32, TypedValueKind::Unsigned32, TypedValueKind::Pointer } },
    { 29664, "d2d1.dll", "D2D1MakeRotateMatrix", TypedValueKind::Void, 3, { TypedValueKind::Float32, TypedValueKind::Point2F, TypedValueKind::Pointer } },
    { 29668, "d2d1.dll", "D2D1Vec3Length", TypedValueKind::Float32, 3, { TypedValueKind::Float32, TypedValueKind::Float32, TypedValueKind::Float32 } },
    { 4709, "user32.dll", "EnumChildWindows", TypedValueKind::Signed32, 3, { TypedValueKind::Pointer, TypedValueKind::Pointer, TypedValueKind::SignedPointer } },
};
inline const TypedAbiMetadata* FindTypedAbi(std::uint16_t id)
{
    const TypedAbiMetadata* result = nullptr;
    for (const auto& entry : TypedAbiContracts)
    {
        if (entry.Id == id)
        {
            result = &entry;
            break;
        }
    }
    return result;
}
}
