// Generated by tools/def-validator/generate-agent-hook-definitions.mjs. Do not edit manually.
#include <Windows.h>

#include <cstddef>
#include <cstdint>

extern "C" std::uintptr_t KnMonInvokeGeneratedValueHookByIndex(
    std::size_t index,
    std::uintptr_t arg0,
    std::uintptr_t arg1,
    std::uintptr_t arg2,
    std::uintptr_t arg3,
    std::uintptr_t arg4,
    std::uintptr_t arg5,
    std::uintptr_t arg6,
    std::uintptr_t arg7,
    std::uintptr_t arg8,
    std::uintptr_t arg9,
    std::uintptr_t arg10,
    std::uintptr_t arg11,
    std::uintptr_t arg12,
    std::uintptr_t arg13,
    std::uintptr_t arg14,
    std::uintptr_t arg15,
    std::uintptr_t arg16
);

extern "C" void KnMonInvokeGeneratedVoidHookByIndex(
    std::size_t index,
    std::uintptr_t arg0,
    std::uintptr_t arg1,
    std::uintptr_t arg2,
    std::uintptr_t arg3,
    std::uintptr_t arg4,
    std::uintptr_t arg5,
    std::uintptr_t arg6,
    std::uintptr_t arg7,
    std::uintptr_t arg8,
    std::uintptr_t arg9,
    std::uintptr_t arg10,
    std::uintptr_t arg11,
    std::uintptr_t arg12,
    std::uintptr_t arg13,
    std::uintptr_t arg14,
    std::uintptr_t arg15,
    std::uintptr_t arg16
);

extern "C" double KnMonInvokeGeneratedDoubleHookByIndex(
    std::size_t index,
    double arg0,
    double arg1
);

std::uintptr_t WINAPI HookedGeneratedApi30249_D3DX10CompileFromFileA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29696, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30250_D3DX10CompileFromFileW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29697, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30251_D3DX10CompileFromMemory(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29698, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30252_D3DX10CompileFromResourceA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29699, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30253_D3DX10CompileFromResourceW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29700, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30254_D3DX10ComputeNormalMap(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29701, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30255_D3DX10CreateAsyncCompilerProcessor(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29702, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30256_D3DX10CreateAsyncEffectCreateProcessor(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29703, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30257_D3DX10CreateAsyncEffectPoolCreateProcessor(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29704, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30258_D3DX10CreateAsyncFileLoaderA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29705, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30259_D3DX10CreateAsyncFileLoaderW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29706, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30260_D3DX10CreateAsyncMemoryLoader(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29707, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30261_D3DX10CreateAsyncResourceLoaderA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29708, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30262_D3DX10CreateAsyncResourceLoaderW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29709, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30263_D3DX10CreateAsyncShaderPreprocessProcessor(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29710, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30264_D3DX10CreateAsyncShaderResourceViewProcessor(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29711, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30265_D3DX10CreateAsyncTextureInfoProcessor(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29712, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30266_D3DX10CreateAsyncTextureProcessor(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29713, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30267_D3DX10CreateEffectFromFileA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29714, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30268_D3DX10CreateEffectFromFileW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29715, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30269_D3DX10CreateEffectFromMemory(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29716, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30270_D3DX10CreateEffectFromResourceA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29717, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30271_D3DX10CreateEffectFromResourceW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29718, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30272_D3DX10CreateEffectPoolFromFileA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29719, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30273_D3DX10CreateEffectPoolFromFileW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29720, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30274_D3DX10CreateEffectPoolFromMemory(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29721, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30275_D3DX10CreateEffectPoolFromResourceA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29722, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30276_D3DX10CreateEffectPoolFromResourceW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29723, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30277_D3DX10CreateFontA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29724, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30278_D3DX10CreateFontIndirectA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29725, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30279_D3DX10CreateFontIndirectW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29726, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30280_D3DX10CreateFontW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29727, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30281_D3DX10CreateMesh(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29728, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30282_D3DX10CreateShaderResourceViewFromFileA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29729, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30283_D3DX10CreateShaderResourceViewFromFileW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29730, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30284_D3DX10CreateShaderResourceViewFromMemory(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29731, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30285_D3DX10CreateShaderResourceViewFromResourceA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29732, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30286_D3DX10CreateShaderResourceViewFromResourceW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29733, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30287_D3DX10CreateSkinInfo(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29734, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30288_D3DX10CreateSprite(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29735, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30289_D3DX10CreateTextureFromFileA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29736, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30290_D3DX10CreateTextureFromFileW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29737, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30291_D3DX10CreateTextureFromMemory(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29738, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30292_D3DX10CreateTextureFromResourceA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29739, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30293_D3DX10CreateTextureFromResourceW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29740, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30294_D3DX10CreateThreadPump(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29741, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30295_D3DX10DisassembleEffect(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29742, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30296_D3DX10DisassembleShader(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29743, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30297_D3DX10FilterTexture(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29744, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30298_D3DX10GetDriverLevel(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29745, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30299_D3DX10GetImageInfoFromFileA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29746, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30300_D3DX10GetImageInfoFromFileW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29747, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30301_D3DX10GetImageInfoFromMemory(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29748, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30302_D3DX10GetImageInfoFromResourceA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29749, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30303_D3DX10GetImageInfoFromResourceW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29750, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30304_D3DX10LoadTextureFromTexture(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29751, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30305_D3DX10PreprocessShaderFromFileA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29752, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30306_D3DX10PreprocessShaderFromFileW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29753, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30307_D3DX10PreprocessShaderFromMemory(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29754, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30308_D3DX10PreprocessShaderFromResourceA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29755, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30309_D3DX10PreprocessShaderFromResourceW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29756, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30310_D3DX10ReflectShader(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29757, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30311_D3DX10SaveTextureToFileA(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29758, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30312_D3DX10SaveTextureToFileW(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29759, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30313_D3DX10SaveTextureToMemory(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29760, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30314_D3DX10SHProjectCubeMap(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29761, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30315_D3DX10UnsetAllDeviceObjects(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29762, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30316_D3DXBoxBoundProbe(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29763, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30317_D3DXColorAdjustContrast(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29764, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30318_D3DXColorAdjustSaturation(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29765, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30319_D3DXComputeBoundingBox(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29766, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30320_D3DXComputeBoundingSphere(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29767, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30321_D3DXCpuOptimizations(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29768, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30322_D3DXCreateMatrixStack(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29769, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30323_D3DXFloat16To32Array(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29770, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30324_D3DXFloat32To16Array(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29771, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30325_D3DXFresnelTerm(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29772, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30326_D3DXIntersectTri(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29773, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30327_D3DXMatrixAffineTransformation(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29774, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30328_D3DXMatrixAffineTransformation2D(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29775, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30329_D3DXMatrixDecompose(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29776, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

std::uintptr_t WINAPI HookedGeneratedApi30330_D3DXMatrixDeterminant(std::uintptr_t arg0, std::uintptr_t arg1, std::uintptr_t arg2, std::uintptr_t arg3, std::uintptr_t arg4, std::uintptr_t arg5, std::uintptr_t arg6, std::uintptr_t arg7, std::uintptr_t arg8, std::uintptr_t arg9, std::uintptr_t arg10, std::uintptr_t arg11, std::uintptr_t arg12, std::uintptr_t arg13, std::uintptr_t arg14, std::uintptr_t arg15)
{
    return KnMonInvokeGeneratedValueHookByIndex(29777, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, 0);
}

extern "C" void* KnMonGetGeneratedHookAddressChunk58(std::size_t localIndex)
{
    switch (localIndex)
    {
    case 0:
        return reinterpret_cast<void*>(HookedGeneratedApi30249_D3DX10CompileFromFileA);
    case 1:
        return reinterpret_cast<void*>(HookedGeneratedApi30250_D3DX10CompileFromFileW);
    case 2:
        return reinterpret_cast<void*>(HookedGeneratedApi30251_D3DX10CompileFromMemory);
    case 3:
        return reinterpret_cast<void*>(HookedGeneratedApi30252_D3DX10CompileFromResourceA);
    case 4:
        return reinterpret_cast<void*>(HookedGeneratedApi30253_D3DX10CompileFromResourceW);
    case 5:
        return reinterpret_cast<void*>(HookedGeneratedApi30254_D3DX10ComputeNormalMap);
    case 6:
        return reinterpret_cast<void*>(HookedGeneratedApi30255_D3DX10CreateAsyncCompilerProcessor);
    case 7:
        return reinterpret_cast<void*>(HookedGeneratedApi30256_D3DX10CreateAsyncEffectCreateProcessor);
    case 8:
        return reinterpret_cast<void*>(HookedGeneratedApi30257_D3DX10CreateAsyncEffectPoolCreateProcessor);
    case 9:
        return reinterpret_cast<void*>(HookedGeneratedApi30258_D3DX10CreateAsyncFileLoaderA);
    case 10:
        return reinterpret_cast<void*>(HookedGeneratedApi30259_D3DX10CreateAsyncFileLoaderW);
    case 11:
        return reinterpret_cast<void*>(HookedGeneratedApi30260_D3DX10CreateAsyncMemoryLoader);
    case 12:
        return reinterpret_cast<void*>(HookedGeneratedApi30261_D3DX10CreateAsyncResourceLoaderA);
    case 13:
        return reinterpret_cast<void*>(HookedGeneratedApi30262_D3DX10CreateAsyncResourceLoaderW);
    case 14:
        return reinterpret_cast<void*>(HookedGeneratedApi30263_D3DX10CreateAsyncShaderPreprocessProcessor);
    case 15:
        return reinterpret_cast<void*>(HookedGeneratedApi30264_D3DX10CreateAsyncShaderResourceViewProcessor);
    case 16:
        return reinterpret_cast<void*>(HookedGeneratedApi30265_D3DX10CreateAsyncTextureInfoProcessor);
    case 17:
        return reinterpret_cast<void*>(HookedGeneratedApi30266_D3DX10CreateAsyncTextureProcessor);
    case 18:
        return reinterpret_cast<void*>(HookedGeneratedApi30267_D3DX10CreateEffectFromFileA);
    case 19:
        return reinterpret_cast<void*>(HookedGeneratedApi30268_D3DX10CreateEffectFromFileW);
    case 20:
        return reinterpret_cast<void*>(HookedGeneratedApi30269_D3DX10CreateEffectFromMemory);
    case 21:
        return reinterpret_cast<void*>(HookedGeneratedApi30270_D3DX10CreateEffectFromResourceA);
    case 22:
        return reinterpret_cast<void*>(HookedGeneratedApi30271_D3DX10CreateEffectFromResourceW);
    case 23:
        return reinterpret_cast<void*>(HookedGeneratedApi30272_D3DX10CreateEffectPoolFromFileA);
    case 24:
        return reinterpret_cast<void*>(HookedGeneratedApi30273_D3DX10CreateEffectPoolFromFileW);
    case 25:
        return reinterpret_cast<void*>(HookedGeneratedApi30274_D3DX10CreateEffectPoolFromMemory);
    case 26:
        return reinterpret_cast<void*>(HookedGeneratedApi30275_D3DX10CreateEffectPoolFromResourceA);
    case 27:
        return reinterpret_cast<void*>(HookedGeneratedApi30276_D3DX10CreateEffectPoolFromResourceW);
    case 28:
        return reinterpret_cast<void*>(HookedGeneratedApi30277_D3DX10CreateFontA);
    case 29:
        return reinterpret_cast<void*>(HookedGeneratedApi30278_D3DX10CreateFontIndirectA);
    case 30:
        return reinterpret_cast<void*>(HookedGeneratedApi30279_D3DX10CreateFontIndirectW);
    case 31:
        return reinterpret_cast<void*>(HookedGeneratedApi30280_D3DX10CreateFontW);
    case 32:
        return reinterpret_cast<void*>(HookedGeneratedApi30281_D3DX10CreateMesh);
    case 33:
        return reinterpret_cast<void*>(HookedGeneratedApi30282_D3DX10CreateShaderResourceViewFromFileA);
    case 34:
        return reinterpret_cast<void*>(HookedGeneratedApi30283_D3DX10CreateShaderResourceViewFromFileW);
    case 35:
        return reinterpret_cast<void*>(HookedGeneratedApi30284_D3DX10CreateShaderResourceViewFromMemory);
    case 36:
        return reinterpret_cast<void*>(HookedGeneratedApi30285_D3DX10CreateShaderResourceViewFromResourceA);
    case 37:
        return reinterpret_cast<void*>(HookedGeneratedApi30286_D3DX10CreateShaderResourceViewFromResourceW);
    case 38:
        return reinterpret_cast<void*>(HookedGeneratedApi30287_D3DX10CreateSkinInfo);
    case 39:
        return reinterpret_cast<void*>(HookedGeneratedApi30288_D3DX10CreateSprite);
    case 40:
        return reinterpret_cast<void*>(HookedGeneratedApi30289_D3DX10CreateTextureFromFileA);
    case 41:
        return reinterpret_cast<void*>(HookedGeneratedApi30290_D3DX10CreateTextureFromFileW);
    case 42:
        return reinterpret_cast<void*>(HookedGeneratedApi30291_D3DX10CreateTextureFromMemory);
    case 43:
        return reinterpret_cast<void*>(HookedGeneratedApi30292_D3DX10CreateTextureFromResourceA);
    case 44:
        return reinterpret_cast<void*>(HookedGeneratedApi30293_D3DX10CreateTextureFromResourceW);
    case 45:
        return reinterpret_cast<void*>(HookedGeneratedApi30294_D3DX10CreateThreadPump);
    case 46:
        return reinterpret_cast<void*>(HookedGeneratedApi30295_D3DX10DisassembleEffect);
    case 47:
        return reinterpret_cast<void*>(HookedGeneratedApi30296_D3DX10DisassembleShader);
    case 48:
        return reinterpret_cast<void*>(HookedGeneratedApi30297_D3DX10FilterTexture);
    case 49:
        return reinterpret_cast<void*>(HookedGeneratedApi30298_D3DX10GetDriverLevel);
    case 50:
        return reinterpret_cast<void*>(HookedGeneratedApi30299_D3DX10GetImageInfoFromFileA);
    case 51:
        return reinterpret_cast<void*>(HookedGeneratedApi30300_D3DX10GetImageInfoFromFileW);
    case 52:
        return reinterpret_cast<void*>(HookedGeneratedApi30301_D3DX10GetImageInfoFromMemory);
    case 53:
        return reinterpret_cast<void*>(HookedGeneratedApi30302_D3DX10GetImageInfoFromResourceA);
    case 54:
        return reinterpret_cast<void*>(HookedGeneratedApi30303_D3DX10GetImageInfoFromResourceW);
    case 55:
        return reinterpret_cast<void*>(HookedGeneratedApi30304_D3DX10LoadTextureFromTexture);
    case 56:
        return reinterpret_cast<void*>(HookedGeneratedApi30305_D3DX10PreprocessShaderFromFileA);
    case 57:
        return reinterpret_cast<void*>(HookedGeneratedApi30306_D3DX10PreprocessShaderFromFileW);
    case 58:
        return reinterpret_cast<void*>(HookedGeneratedApi30307_D3DX10PreprocessShaderFromMemory);
    case 59:
        return reinterpret_cast<void*>(HookedGeneratedApi30308_D3DX10PreprocessShaderFromResourceA);
    case 60:
        return reinterpret_cast<void*>(HookedGeneratedApi30309_D3DX10PreprocessShaderFromResourceW);
    case 61:
        return reinterpret_cast<void*>(HookedGeneratedApi30310_D3DX10ReflectShader);
    case 62:
        return reinterpret_cast<void*>(HookedGeneratedApi30311_D3DX10SaveTextureToFileA);
    case 63:
        return reinterpret_cast<void*>(HookedGeneratedApi30312_D3DX10SaveTextureToFileW);
    case 64:
        return reinterpret_cast<void*>(HookedGeneratedApi30313_D3DX10SaveTextureToMemory);
    case 65:
        return reinterpret_cast<void*>(HookedGeneratedApi30314_D3DX10SHProjectCubeMap);
    case 66:
        return reinterpret_cast<void*>(HookedGeneratedApi30315_D3DX10UnsetAllDeviceObjects);
    case 67:
        return reinterpret_cast<void*>(HookedGeneratedApi30316_D3DXBoxBoundProbe);
    case 68:
        return reinterpret_cast<void*>(HookedGeneratedApi30317_D3DXColorAdjustContrast);
    case 69:
        return reinterpret_cast<void*>(HookedGeneratedApi30318_D3DXColorAdjustSaturation);
    case 70:
        return reinterpret_cast<void*>(HookedGeneratedApi30319_D3DXComputeBoundingBox);
    case 71:
        return reinterpret_cast<void*>(HookedGeneratedApi30320_D3DXComputeBoundingSphere);
    case 72:
        return reinterpret_cast<void*>(HookedGeneratedApi30321_D3DXCpuOptimizations);
    case 73:
        return reinterpret_cast<void*>(HookedGeneratedApi30322_D3DXCreateMatrixStack);
    case 74:
        return reinterpret_cast<void*>(HookedGeneratedApi30323_D3DXFloat16To32Array);
    case 75:
        return reinterpret_cast<void*>(HookedGeneratedApi30324_D3DXFloat32To16Array);
    case 76:
        return reinterpret_cast<void*>(HookedGeneratedApi30325_D3DXFresnelTerm);
    case 77:
        return reinterpret_cast<void*>(HookedGeneratedApi30326_D3DXIntersectTri);
    case 78:
        return reinterpret_cast<void*>(HookedGeneratedApi30327_D3DXMatrixAffineTransformation);
    case 79:
        return reinterpret_cast<void*>(HookedGeneratedApi30328_D3DXMatrixAffineTransformation2D);
    case 80:
        return reinterpret_cast<void*>(HookedGeneratedApi30329_D3DXMatrixDecompose);
    case 81:
        return reinterpret_cast<void*>(HookedGeneratedApi30330_D3DXMatrixDeterminant);
    default:
        break;
    }

    return nullptr;
}
